/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SsesAmbulanceWlList {
    }
}
declare global {
    interface HTMLSsesAmbulanceWlListElement extends Components.SsesAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLSsesAmbulanceWlListElement: {
        prototype: HTMLSsesAmbulanceWlListElement;
        new (): HTMLSsesAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "sses-ambulance-wl-list": HTMLSsesAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface SsesAmbulanceWlList {
    }
    interface IntrinsicElements {
        "sses-ambulance-wl-list": SsesAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sses-ambulance-wl-list": LocalJSX.SsesAmbulanceWlList & JSXBase.HTMLAttributes<HTMLSsesAmbulanceWlListElement>;
        }
    }
}
